### ISSUE TITLE
No podspec found for `image_picker_web` in `.symlinks/plugins/image_picker_web/ios`

### ISSUE THREAD

**Issue by kgsachinthaudara** [Ahmadre/image_picker_web#11]
when I running pod install this plugin fail

`No podspec found for 'image_picker_web' in '.symlinks/plugins/image_picker_web/ios'`

**`flutter doctor` summary**

<img width="601" alt="Screenshot 2020-05-21 at 10 27 25" src="https://user-images.githubusercontent.com/40377926/82524945-ce0d8100-9b4d-11ea-995a-d0ac3a1720de.png">

my question how do I keep web plugging  separately for flutter project ?

**Comment by Ahmadre** [comment]
Thank you so much for raising this issue. It's very imported to me to fix this.
 
I'll response to this, after it's solved.

Best regards.

PS: Flutter Team and contributors are working now on a official image_picker for web: https://github.com/rodydavis/flutter_plugins/commits/image-picker-web

**Comment by Ahmadre** [comment]
Image_Picker is officially supported by web: https://pub.dev/packages/image_picker#deprecation-warnings-in-pickimage-pickvideo-and-lostdataresponse

Please use this official plugin.
