### ISSUE TITLE
image file are corrupted

### ISSUE THREAD

**Issue by shinriyo** [Ahmadre/image_picker_web#14]
I used the plugin.
And I choose this
html.File mediaFile =
        new html.File(mediaData.data, mediaData.fileName, {'type': mimeType})

from Full Example in README

And I uploaded to Firebase Storage
but image file was broken
same person is here
https://stackoverflow.com/questions/60719724/flutter-web-upload-to-firestore

**Comment by Antonwy** [comment]
Any news on this problem?
