### ISSUE TITLE
iOS build issue which image_picker_web in pubspec.yaml

### ISSUE THREAD

**Issue by wterrill** [Ahmadre/image_picker_web#16]
First, thanks so much for the plugin.  This will become more popular as flutter web becomes more common.

Currently I have:
image_picker_web: ^1.0.9 in my pubspec.yaml file. 

When building for iOS, I get the following error:
```
[ios/.symlinks/plugins/image_picker_web/example] flutter pub get
Running "flutter pub get" in example...                         
Cannot open file, path = '/Users/username/.pub-cache/global_packages/image_picker_web_example/pubspec.lock' (OS Error: No such file or directory, errno = 2)
pub get failed (66; Cannot open file, path = '/Users/username/.pub-cache/global_packages/image_picker_web_example/pubspec.lock' (OS Error: No such file or directory, errno = 2))
exit code 66
```
Since iOS isn't supported by this plugin, I took out all references in my code to the image_picker_web package, but I still get the error.  The only way to avoid it is to comment out image_picker_web: ^1.0.9  in my pubspec.yaml and run 'flutter pub get'

I was hoping to use the kIsWeb boolean to decide whether or not to use image_picker or image_picker_web package... but it looks like when image_picker_web is in the pubspec.yaml file, the project can't be built for iOS.

Just to be clear, I'm not looking for any functionality for ios... I'm just hoping to be able to build with the package in the pubspec file. (and then, avoid that code with the kIsWeb boolean.

Any help would be appreciated.

**Comment by dimitristaufer** [comment]
I just spent several hours trying to solve the same problem.

@wterrill Have you had any success meanwhile?

@Ahmadre I'd appreciate any ideas.

Thanks for this plugin!

**Comment by wterrill** [comment]
I have not.  I had to abandon trying to make them both work.  I imagine this will become more of a problem when flutter web comes out of beta

**Comment by vinnytwice** [comment]
Hi, @Ahmadre commented here https://github.com/Ahmadre/image_picker_web/issues/11 that web is now supported by official picker_image plugin, but it doesn't look it's the case at all, so yes, for now the only way to pic an image on web is this plugin, but when running it on iOs comment it out in pubspec.yaml. 
It's a shame.

**Comment by secreal** [comment]
i create helper to move all image picker web import in one place
and call this method on all my dart file using
`Uint8List imageByte = await imagePickerWeb();`

ImagePickerWeb.dart
```
import 'dart:typed_data';
  /* comment this line for android/ios build */
 import 'package:image_picker_web/image_picker_web.dart';

Future<Uint8List> imagePickerWeb() async {
  var result = new Uint8List(0);
 /* comment this line for android/ios build */
  result = await ImagePickerWeb.getImage(outputType: ImageType.bytes);
  return result;
}
```

then, when I want to build android / ios, I comment  pubspec.yaml and the method here
hope that help
