### ISSUE TITLE
ImagePickerWeb.getImage(outputType: ImageType.file);

### ISSUE THREAD

**Issue by carmas123** [Ahmadre/image_picker_web#17]
Sorry man I try to use you lib but when I try to get file name from picked file I got a problem.
The result html.File contains "name" property but this contain only the filename and not the full path, also the "relativePath" is always empty.

**Comment by mellowcello77** [comment]
Yip, relative path is empty. Anyone know why?

**Comment by mellowcello77** [comment]
Debug shows

<error>:<getObject: NoSuchMethodError: The getter 'uri' was called on null.>

When doing:


  Future<void> _getImgFile() async {
    html.File infos = await ImagePickerWeb.getImage(outputType: ImageType.file);
    setState(() => _imageInfo = 'Name: ${infos.name}\nRelative Path: ${infos.relativePath}');
    print(_imageInfo);
  }

**Comment by TesteurManiak** [comment]
Just tested the example in a Chrome browser and I don't have any error log, could you please provide the output of your `flutter doctor -v`. Here's mine if you want to compare :
```bash
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [version 10.0.19042.928], locale fr-FR)
    • Flutter version 2.0.4 at C:\src\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Guillaume\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```

**Comment by TesteurManiak** [comment]
About the relative path being empty it is likely that it is because of how browsers' security work as you don't have access to the file-system, while you are able to read some data everything is not available.
