### ISSUE TITLE
Official image_picker vs image_picker_web

### ISSUE THREAD

**Issue by mzimbres** [Ahmadre/image_picker_web#19]
Hi, is this plugin still needed after the official `image_picker` added support for web through the `getImage` function? How do they differ? Thanks

**Comment by Ahmadre** [comment]
Hi @mzimbres 

congratulations, that you found the official implementation.

I wouldn't recommend to use this package, use the official Image_Picker. They implemented an interface of image_picker including the new: PickedFile.

Archiving this package due to this.

Thanks for your reminder :).
