### ISSUE TITLE
File Type

### ISSUE THREAD

**Issue by jobsyNZ** [Ahmadre/image_picker_web#2]
Have you got plans to have the image to be as file type File?

The mobile version does this, and Firebase Storage Upload requires a File, not an Image.

**Comment by Ahmadre** [comment]
Very good question!

And a quick answer to it:
```dart
import 'package:image_picker_web/image_picker_web.dart';
import 'dart:html' as html;
import 'package:mime_type/mime_type.dart';
import 'package:path/path.dart' as Path;

var mediaData = await ImagePickerWeb.getImageInfo;
    String mimeType = mime(Path.basename(mediaData.fileName));
    html.File mediaFile =
        new html.File(mediaData.data, mediaData.fileName, {'type': mimeType});
```

I release some Flutter Web Apps on Firebase with Images and Videos. That's because this package exists :). Have fun

**Comment by Ahmadre** [comment]
For Video Files you can use this till now:

```dart
Future pickVideoFile() async {
    final html.FileUploadInputElement input = html.FileUploadInputElement();
    input.click();
    await input.onChange.first;
    if (input.files.isEmpty) return null;
    return input.files[0];
  }
```

I will update this package soon to have an option to get only the html.File for both Video and Images. I also encountered that this approach is much faster

**Comment by Ahmadre** [comment]
Add Types and Fixed with v.1.0.2: https://pub.dev/packages/image_picker_web#picking-videos

**Comment by rish07** [comment]
The method above outputs the file type as html.File but FirebaseStorage requires io.File type and hence there's a type mismatch resulting failure of the code.

**Comment by jaxnz** [comment]
Method as mentioned here:

https://github.com/Ahmadre/image_picker_web/issues/8

```
import 'dart:html' as html;
 
import 'package:mime_type/mime_type.dart';
import 'package:path/path.dart' as Path;
import 'package:image_picker_web/image_picker_web.dart';
import 'package:flutter/material.dart';

 html.File _cloudFile;
 var _fileBytes;
 Image _imageWidget;
 
 Future<void> getMultipleImageInfos() async {
    var mediaData = await ImagePickerWeb.getImageInfo;
    String mimeType = mime(Path.basename(mediaData.fileName));
    html.File mediaFile =
        new html.File(mediaData.data, mediaData.fileName, {'type': mimeType});

    if (mediaFile != null) {
      setState(() {
        _cloudFile = mediaFile;
        _fileBytes = mediaData.data;
        _imageWidget = Image.memory(mediaData.data);
      });
    }
  }
```

**Comment by TaikiAsa** [comment]
I use this Method and upload firrebasestorage but image was broken.
Please tell me solution.
