### ISSUE TITLE
More question rather than issue.

### ISSUE THREAD

**Issue by spacekestrel** [Ahmadre/image_picker_web#20]
Is there any way to add multiple images at once with this plugin?

**Comment by TesteurManiak** [comment]
Hi, the project is currently under transition, I am waiting to have the admin rights on pub.dev to publish the 2.0.0 update, for the time being you can use this transitory package https://pub.dev/packages/image_picker_web_redux which is a fork from this repo with the multi image picker.

**Comment by spacekestrel** [comment]
> 
> 
> Hi, the project is currently under transition, I am waiting to have the admin rights on pub.dev to publish the 2.0.0 update, for the time being you can use this transitory package https://pub.dev/packages/image_picker_web_redux which is a fork from this repo with the multi image picker.

thanks a lot, mate.
