### ISSUE TITLE
Not working on Safari (iOS)

### ISSUE THREAD

**Issue by SempaiEcchi** [Ahmadre/image_picker_web#22]
The popup for browsing the gallery doesn’t show on Safari. Is this a known issue or am I doing something wrong?

**Comment by TesteurManiak** [comment]
Oh it should have been fixed but if you still encounter issues I am going to investigate it. Safari is known for having a different behavior than other browsers and need some specific code. Can you precise the method you tried ?

**Comment by SempaiEcchi** [comment]
I am using the method to get the image as bytes.

**Comment by TesteurManiak** [comment]
Okay the fix made to work on Safari is only for the multi image picker, I am going to work on a fix for the single image picker.

**Comment by TesteurManiak** [comment]
It should be fixed on the main branch now, can you test it and confirm if it is working in your case so I can add the changes in the next release of the package.

**Comment by TesteurManiak** [comment]
The fix has been published in the new release [2.0.2](https://github.com/Ahmadre/image_picker_web/releases/tag/2.0.2) and should be [available on Pub.dev](https://pub.dev/packages/image_picker_web/versions/2.0.2) too. I am closing the issue, do not hesitate to reopen it if the issue remains.
