### ISSUE TITLE
[Suggestion] Make it type safe

### ISSUE THREAD

**Issue by itsJoKr** [Ahmadre/image_picker_web#29]
Since method getImage accepts enum, the return value is of `Object?`. This is a bit confusing.

I suggest to leverage types and create three different methods, example:

```
Future<Uint8List> getImageAsBytes();

Future<File> getImageAsFile();

Future<Widget> getImageAsWidget();
```

What do you think?

**Comment by TesteurManiak** [comment]
This is a good idea, and the method getImage would be deprecated then.
