### ISSUE TITLE
Can you make an universal version?

### ISSUE THREAD

**Issue by Dorbmon** [Ahmadre/image_picker_web#3]
On the android,the program use this library can't get through the compiling.
Can you make it does nothing on Android but can pass the Android compiling?

**Comment by Ahmadre** [comment]
I already answered that question here: https://github.com/Ahmadre/image_picker_web/issues/1

It's not possible! Flutter Team can't do that till now because of a lot of things that have to be done/thinking of. Separate your project to web and native!

**Comment by gazialankus** [comment]
What specifically prevents making this compile with mobile? Can we not use conditional imports to make it compile in mobile?
