### ISSUE TITLE
Cannot run / build for web

### ISSUE THREAD

**Issue by praharshbhatt** [Ahmadre/image_picker_web#31]
```
[🔴] × flutter build web

💪 Building with sound null safety 💪

Target dart2js failed: Exception: /home/praharshb/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.4/lib/image_picker_for_web.dart:246:23:
Error: 'is' can't be used as an identifier because it's a keyword.
      if (!_completer.is Completed && files != null) {
                      ^^
/home/praharshb/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.4/lib/image_picker_for_web.dart:246:26:
Error: Expected ')' before this.
      if (!_completer.is Completed && files != null) {
                         ^^^^^^^^^
/home/praharshb/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.4/lib/image_picker_for_web.dart:246:23:
Error: The getter 'is' isn't defined for the class 'Completer<PickedFile>'.
 - 'Completer' is from 'dart:async'.
 - 'PickedFile' is from 'package:image_picker_platform_interface/src/types/picked_file/html.dart'
 ('/home/praharshb/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_platform_interface-2.4.1/lib/src/types/picked_file/html.dart').
      if (!_completer.is Completed && files != null) {
                      ^^
/home/praharshb/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.4/lib/image_picker_for_web.dart:248:42:
Error: Property 'first' cannot be accessed on 'List<File>?' because it is potentially null.
 - 'List' is from 'dart:core'.
 - 'File' is from 'dart:html'.
          html.Url.createObjectUrl(files.first),
                                         ^^^^^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                             10.6s
Exception: Failed to compile application for the Web.
```

**Comment by TesteurManiak** [comment]
Please add more details to your issue such as the package version you are using and your Flutter version. A minimal reproductible code sample would be great too.

**Comment by praharshbhatt** [comment]
I retried after changing systems and compiled it perfectly. I think it's an issue in Flutter installation? In any case, should not be relevant here.
Thanks, closing for now.

**Comment by mohamadhadibi** [comment]
> I retried after changing systems and compiled it perfectly. I think it's an issue in Flutter installation? In any case, should not be relevant here. Thanks, closing for now.

Hi, I don't know what do you mean by "changing systems". but I have the same problem and I can't solve it by now.
so I recommend to reopen the issue please.

**Comment by mohamadhadibi** [comment]
my flutter & dart versions :
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (6 months ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2



project:
environment:
  sdk: ">=2.17.1 <3.0.0"



error complete info:


/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:144:17: Error: Type 'Uint8List' not found.
  static Future<Uint8List?> getImageAsBytes() async {
                ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:176:22: Error: Type 'Uint8List' not found.
  static Future<List<Uint8List>?> getMultiImagesAsBytes() async {
                     ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:207:17: Error: Type 'Uint8List' not found.
  static Future<Uint8List?> getVideoAsBytes() async {
                ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:233:22: Error: Type 'Uint8List' not found.
  static Future<List<Uint8List>?> getMultiVideosAsBytes() async {
                     ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:179:18: Error: 'Uint8List' isn't a type.
    var files = <Uint8List>[];
                 ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:191:18: Error: 'Uint8List' isn't a type.
    var files = <Uint8List>[];
                 ^^^^^^^^^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:196:49: Error: The argument type 'Object?' can't be assigned to the parameter type 'Uint8List'.
 - 'Object' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
    return files.map<Image>((e) => Image.memory(e)).toList();
                                                ^
/F:/Softwares/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_web-3.0.0+1/lib/image_picker_web.dart:236:18: Error: 'Uint8List' isn't a type.
    var files = <Uint8List>[];
                 ^^^^^^^^^
Failed to compile application.
