### ISSUE TITLE
Resizing images picked

### ISSUE THREAD

**Issue by andrewpmoore** [Ahmadre/image_picker_web#4]
Hi
The picker is working fine, but before uploading images I'm wanting to resize them.

I'm trying the following

```
var bytes = await ImagePickerWeb.getImage(outputType: ImageType.bytes, );
img.Image imageTemp = img.decodeImage(bytes);
img.Image resizedImg = img.copyResize(imageTemp, width: size) ;
Uint8List newBytes = resizedImg.getBytes(format: img.Format.rgb);
```

but the list I get back seems to be in a different format to the original "bytes" returned as I can't then load them into a preview image.

Do you know of an effective way to resize the images returned from the picker. I'm happy to use any ImageType return type as I've been trying several methods to resize.

**Comment by andrewpmoore** [comment]
Found the issue, I needed to encode the image again, so replacing the last line in the example above fixes it

`Uint8List newBytes = img.encodeJpg(resizedImg, quality: 60);`

**Comment by Ahmadre** [comment]
Sorry for answering so late. Somehow I don't get any notifications from github.

But what you mention could be a new feature that could be useful for others.

If you don't mind I'll try to find some time to integrate a quality parameter (0.0 - 1.0) like iOS is providing.

Thanks!
