### ISSUE TITLE
MissingPluginException(No implementation found for method pickImage on channel image_picker_web)

### ISSUE THREAD

**Issue by samoray1998** [Ahmadre/image_picker_web#40]
this exception happened to me after ,i deploy my app to server  do u have guys any idea how to solve that

**Comment by TesteurManiak** [comment]
Please provide a minimal reproducible code sample of your issue. Does it happen only when your app is deployed or also when you run the app locally ?

**Comment by TesteurManiak** [comment]
Without more information I'm closing this issue.
