### ISSUE TITLE
LRV

### ISSUE THREAD

**Issue by MauroGentile** [Ahmadre/image_picker_web#42]
the ImagePickerWeb.getMultiVideosAsFile doesn't allow picking LRV files.  Is it possible?

**Comment by TesteurManiak** [comment]
The picker is using the `video/*` file type specifier as defined in [mdn web doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers) if LRV files are not recognized it means that your browser is not recognizing it as being a video file. This is not related to the package.
