### ISSUE TITLE
Convert Uint8List to String from await ImagePickerWeb.getImageAsBytes()

### ISSUE THREAD

**Issue by markbulingit** [Ahmadre/image_picker_web#43]
I am trying to convert Uint8List to string and vice-versa so I can easily assign it to MemoryImage

final temp = await ImagePickerWeb.getImageAsBytes();

But after making many attempts the encoded and decoded Uint8List simply won't work.
Is there a right way to do this?

**Comment by TesteurManiak** [comment]
This has nothing to do with the scope of this package.
