### ISSUE TITLE
Target crashed

### ISSUE THREAD

**Issue by MauroGentile** [Ahmadre/image_picker_web#45]
As part of a Flutter web application, I allow authenticated users to pick multiple large (~4Gb) mp4 files and upload them to Google storage.

I first picked the file: 
```
List<html.File>? picked =
                      await ImagePickerWeb.getMultiVideosAsFile();
```
 And then upload them though via putFile. 
In some cases, the upload crashed with the message "Debugger: Target crashed!!!"

I opened a issue to Firebase/Flutterfire https://github.com/firebase/flutterfire/issues/11341 initially believing it was their problem.

But following their instructions, we made some tests which seems to point image_web_picker as responsible for the issue.
Please refer to the link provided above for the details.

I would be thankful if you could assist to solve this problem

**Comment by TesteurManiak** [comment]
This looks similar to this issue https://github.com/Ahmadre/image_picker_web/issues/35
Have you checked the [big_video_upload example](https://github.com/Ahmadre/image_picker_web/blob/master/example/lib/big_video_upload/big_video_upload_view.dart) and tried to use `FileReader` to see if it helped?

**Comment by MauroGentile** [comment]
Hello @TesteurManiak First of all thank you for your prompt answer.
I tried the snippet. On the problematic file I get the exact same problem: Debugger: Target crashed!

**Comment by TesteurManiak** [comment]
From what I understand this bug happens with specific files, do you think you'd be able to share one of those files so I'll be able to reproduce this behavior?

**Comment by MauroGentile** [comment]
hello, 
yes, that's correct: the problem happens with specific mp4 files that apparently have no problem. 

Reporting what I wrote in the flutterfire ticket:
The problem occurs only for some files. Most of the time it does not pop up.
The problematic MP4 file is not corrupted (we can watch the content).
The file is less than half the size of the files I usually load successfully (1.6 vs. 4 GB).
The error is persistent, which means that a problematic file ALWAYS throws an error, so it cannot be a network problem.
The error occurs both on different computers also in different networks) and on different browsers.
The problematic file can be loaded to GCP without problems either from the shell using normal gsutils or using the python API.

Yes, I can share the file with you, but not publicly: it is a video a customer shared with us, authorizing us to share only to debug the issue. May I send you the link by email?

**Comment by TesteurManiak** [comment]
You can share it to me at the email address in my profile
