### ISSUE TITLE
The App Frequently Crashes When Taking Photos with the Camera on Android

### ISSUE THREAD

**Issue by morio77** [Ahmadre/image_picker_web#46]
1. Implement the following code.
2. Deploy it as a web application.
3. Access it using a low-spec Android smartphone and take a photo.

```dart
class ImagePickerTest extends StatelessWidget {
  const ImagePickerTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: IconButton(
        onPressed: () async {
          await ImagePicker().pickImage(
            source: ImageSource.camera,
            imageQuality: 10,
          );
        },
        icon: const Icon(Icons.camera_alt_sharp),
      )),
    );
  }
}
```

Expectation:  
I suspect it is due to memory shortage causing other activities to be killed.

Remarks:  
* It happens frequently on Chrome, but as of now, it has not occurred on Brave.  
* I Only have a low-spec smartphone.

**Comment by TesteurManiak** [comment]
> It happens frequently on Chrome, but as of now, it has not occurred on Brave.

From your remarks, this seems to be an issue with the browser using too much resources and not an issue with the package itself. There is not a lot of expensive operations in the Dart code of the package that could be improved.

**Comment by morio77** [comment]
Thanks.
