### ISSUE TITLE
dart.html error while build apk

### ISSUE THREAD

**Issue by appfliiq-x** [Ahmadre/image_picker_web#47]
dart.html is not supported in Android & iOS, Can universal_html be used instead since app will not build with dart.html?

when importing image_picker_web in a cross platform app I get this error during build:

`/.pub-cache/hosted/pub.dev/image_picker_web-3.1.1/lib/src/extensions/file_extensions.dart:2:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;`

To fix it I replaced the `import 'dart:html' as html;` to `import "package:universal_html/html.dart" as html;`

**Comment by TesteurManiak** [comment]
I don't like the idea of adding a 3rd party dependency to the package when it's not actually needed.
You should be able to create an interface using conditional imports to compile on mobile platforms instead of relying on universal_html.
