### ISSUE TITLE
getting unnecessary text tagged on top /app bar area of the previous selections of images

### ISSUE THREAD

**Issue by Jaswanth28** [Ahmadre/image_picker_web#48]
getting unnecessary text tagged on top /app bar area of the previous selections of images
![Screenshot 2024-04-09 222953](https://github.com/Ahmadre/image_picker_web/assets/81845691/d9ea28bc-d004-4306-9ba9-c989ea2e7ee0)

**Comment by TesteurManiak** [comment]
Please provide a minimal reproducible code example.
