### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by RajeevRetire100** [Ahmadre/image_picker_web#49]
Any eta for flutter version 3.22.1 compatibility with wasm support

**Comment by TesteurManiak** [comment]
I haven't started working on it.
If anyone wants to work on this and open a PR I'll be glad to review it.

**Comment by TesteurManiak** [comment]
I've quickly investigated the migration requirements to wasm and it seems like there's currently no replacement to the `FileUploadInputElement` class which this package heavily relies on. Not sure that a migration to webassembly is possible for now.

**Comment by bymoye** [comment]
> I've quickly investigated the migration requirements to wasm and it seems like there's currently no replacement to the `FileUploadInputElement` class which this package heavily relies on. Not sure that a migration to webassembly is possible for now.

in 'package:web/web.dart' use HTMLInputElement()..accept = '$type/*'..type = 'file';

**Comment by bymoye** [comment]
I trying to migrate to package:web

**Comment by bymoye** [comment]
#52
