### ISSUE TITLE
Is it possible to get selected image size?

### ISSUE THREAD

**Issue by bssawais** [Ahmadre/image_picker_web#7]
Is it possible to get selected image size? i can get image type but need size as well, any suggestions?

Thanks

**Comment by Ahmadre** [comment]
Hi @bssawais ,

thank you for your feature request.

This package is a reflection of flutter teams: image_picker. So it should be clean and with similar features like native mobile.

What you're searching is not really related to this package, but to Flutter itself. Here's an answer that helps you: 

https://stackoverflow.com/a/44683714/5535773

**Comment by bssawais** [comment]
Thanks
i guess
mediaData.data.length.toString() will do the trick for now :-)
