### ISSUE TITLE
Iphone safari browser is not supported

### ISSUE THREAD

**Issue by sujintao** [Ahmadre/image_picker_web#9]
After using the method in the example, I found that I could not get the picture data with iphone's safari browser, but I could turn on the camera.

**Comment by Ahmadre** [comment]
> After using the method in the example, I found that I could not get the picture data with iphone's safari browser, but I could turn on the camera.

interesting 🤔 Thanks for raising this issue.

Could you please tell me about the device:
- Model
- iOS Version

and your Flutter doctor (`flutter doctor -v`)

Thanks

By the way: this package is very simple and is doing nothing then if you would pick a file through javascript or dart's html/js library. So your issue could be also interesting for all flutter users.

**Comment by Ahmadre** [comment]
Image_Picker is officially supported by web: https://pub.dev/packages/image_picker#deprecation-warnings-in-pickimage-pickvideo-and-lostdataresponse

Please use this official plugin.
